repos:
  -   repo: https://github.com/python/black
      rev: stable
      hooks:
      - id: black
  -   repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
      - id: trailing-whitespace
      # ensures files are either empty or end with a blank line
      - id: end-of-file-fixer
      # valid python file
      - id: check-ast
      # validates style (see setup.cfg for options)
      - id: flake8
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.711
      hooks:
      - id: mypy
